AllCops:
  TargetRubyVersion: '2.6.0'
  Exclude:
    - 'log_parser.gemspec'
    - 'spec/spec_helper.rb'
    - 'spec/helpers.rb'

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/**/*'
